

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:backofficeDb
    # url: jdbc:h2:file:C:\Users\d0d0l\OneDrive\Desktop\zerobase_reponsitory\MyCode\springboot-jpa-examples\BulletinBoardFunction\backofficeDb
    driver-class-name: org.h2.Driver
    username: root
    password: '1111'

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false

    properties:
      format_sql: true
      hibernate:
        show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html
  mail:
    username: d0d0lbangi13@gmail.com
    password: 1111
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
  file:
    name: ./logs/spring-jpa.log


############ 네이버API

naver-app:
  client-id: xxxxxxxxxxxxxxxxxxxx
  client-secret: xxxxxxxxxx


